base_url = "https://fbik.top"
title = "FBIK."
description = "FBIK's personal blog"
default_language = "zh"

compile_sass = false
build_search_index = false
minify_html = true

taxonomies = [{ name = "tags", feed = false }]

generate_feeds = true

[markdown]
render_emoji = false
external_links_target_blank = true
external_links_no_referrer = true

[markdown.highlighting]
light_theme = "github-light"                                                                                     
dark_theme = "github-dark"

[slugify]
paths = "on"
taxonomies = "on"

[extra]
bio = "Minimalism"
nav = [{ name = "home", url = "/" }, { name = "blog", url = "/blog" }, { name = "tags", url = "/tags" },{ name = "friends", url = "/friends" }, { name = "email", url = "mailto:fbik@fbik.top" }]
author = "FBIK."
author_link = "/"
footer = "Copyright 2025 FBIK. All rights reserved.\n\nReproduction requires attribution to the original source."
